version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo:27017/MidTerm
    depends_on:
      - mongo
    networks:
      - app-network 

  mongo:
    image: mongo:6.0
    ports:
      - "28017:27017"
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge 
