version: '3.8'

services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo:27017/MidTerm
    depends_on:
      - mongo
    volumes:
      - ../frontend/views:/usr/src/app/frontend/views
      - ../frontend/public:/usr/src/app/frontend/public
    working_dir: /usr/src/app
    networks:
      - midterm-network 

  backend2:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo:27017/MidTerm
    depends_on:
      - mongo
    volumes:
      - ../frontend/views:/usr/src/app/frontend/views
      - ../frontend/public:/usr/src/app/frontend/public
    working_dir: /usr/src/app
    networks:
      - midterm-network 

  mongo:
    image: mongo:6.0
    ports:
      - "28017:27017"
    networks:
      - midterm-network  
  
  nginx:
    build: 
      context: ../docker/frontend-nginx
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - backend
      - backend2
    networks:
      - midterm-network 
    volumes:
      - ../frontend/views:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  midterm-network:
    driver: bridge 
